# Generated by Django 2.2 on 2020-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundProjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpnlinfo',
            name='day_pnl',
            field=models.FloatField(default=0, verbose_name='当日总盈亏'),
        ),
        migrations.AlterField(
            model_name='fundpnlinfo',
            name='day_pnl_securityalgorithm',
            field=models.FloatField(default=0, verbose_name='当日总盈亏证券算法'),
        ),
        migrations.AlterField(
            model_name='fundpnlinfo',
            name='var',
            field=models.FloatField(default=0, verbose_name='VaR'),
        ),
    ]
